set_property PACKAGE_PIN W7 [get_ports {dispcode[0]}]
set_property PACKAGE_PIN W6 [get_ports {dispcode[1]}]
set_property PACKAGE_PIN U8 [get_ports {dispcode[2]}]
set_property PACKAGE_PIN V8 [get_ports {dispcode[3]}]
set_property PACKAGE_PIN U5 [get_ports {dispcode[4]}]
set_property PACKAGE_PIN V5 [get_ports {dispcode[5]}]
set_property PACKAGE_PIN U7 [get_ports {dispcode[6]}]
set_property PACKAGE_PIN W4 [get_ports {select[3]}]
set_property PACKAGE_PIN V4 [get_ports {select[2]}]
set_property PACKAGE_PIN U4 [get_ports {select[1]}]
set_property PACKAGE_PIN U2 [get_ports {select[0]}]
set_property PACKAGE_PIN T17 [get_ports btn]
set_property PACKAGE_PIN T1 [get_ports button1]
set_property PACKAGE_PIN R2 [get_ports button2]
set_property PACKAGE_PIN W5 [get_ports clock]
set_property PACKAGE_PIN V17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports btn]
set_property IOSTANDARD LVCMOS33 [get_ports button2]
set_property IOSTANDARD LVCMOS33 [get_ports button1]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]


set_property PACKAGE_PIN V7 [get_ports {dispcode[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports testsignal]
set_property PACKAGE_PIN U16 [get_ports testsignal]


